train_dataset:
  glue:
    task: cola 
    tokenizer_name: bert-base-uncased
    split: train
    max_seq_length: 256 
    shuffle: false
    drop_last: false 
val_dataset:
  glue:
    task: cola 
    tokenizer_name: bert-base-uncased
    split: validation 
    max_seq_length: 256 
    shuffle: false
    drop_last: false 
model:
  bert_classification:
    num_labels: 2
    use_pretrained: true 
    tokenizer_name: bert-base-uncased
    pretrained_model_name: bert-base-uncased
optimizer:
  adamw:
    lr: 5.0e-5
    betas:
      - 0.9
      - 0.98
    eps: 1.0e-06
    weight_decay: 0.1
schedulers:
  - warmup:
      warmup_method: linear
      warmup_iters: 0.06dur
      warmup_factor: 0
      interval: step
  - linear_decay:
      start_factor: 1.0
      end_factor: 0.0
      total_iters: 0.94dur
      interval: step
      verbose: false
loggers:
  - file:
      log_level: batch
      filename: stdout
      buffer_size: 1
      flush_every_n_batches: 100
      every_n_batches: 100
      every_n_epochs: 1
  - wandb:
      project: bert
      name: cola 
      extra_init_params: {}
  - tqdm: {}
max_epochs: 5
train_batch_size: 16
eval_batch_size: 16
seed: 19
device:
  gpu: {}
dataloader:
  pin_memory: true
  persistent_workers: true
  num_workers: 8
  timeout: 0
  prefetch_factor: 2
grad_accum: 1
precision: amp
grad_clip_norm: None
validate_every_n_batches: 250 
validate_every_n_epochs: 1
callbacks:
  - lr_monitor: {}
