train_dataset:
  c4:
    split: train
    num_samples: 102400
    max_seq_len: 2048
    tokenizer_name: gpt2
    group_method: concat
    seed: 17
    shuffle: true
    drop_last: true
val_dataset:
  c4:
    split: validation
    num_samples: 10240
    max_seq_len: 2048
    tokenizer_name: gpt2
    group_method: truncate
    seed: 17
    shuffle: false
    drop_last: false
model:
  gpt2:
    use_pretrained: false
    tokenizer_name: gpt2
    gradient_checkpointing: false
    model_config:
      n_embd: 2560
      n_head: 32
      n_layer: 32
      n_positions: 2048
optimizer:
  decoupled_adamw:
    lr: 1.6e-4
    betas:
      - 0.9
      - 0.95
    eps: 1.0e-08
    weight_decay: 0.0
schedulers:
  - cosine_decay_with_warmup:
      t_warmup: 0.1dur
max_duration: 1ep
train_batch_size: 1024
grad_accum: 16
eval_batch_size: 64
seed: 17
device:
  gpu: {}
dataloader:
  pin_memory: true
  persistent_workers: true
  num_workers: 1
  timeout: 0
  prefetch_factor: 2
precision: fp16
deepspeed:
  zero_optimization:
    stage: 2
grad_clip_norm: 1.0
validate_every_n_batches: 1000
validate_every_n_epochs: 1
