train_dataset:
  glue:
    task: mnli
    tokenizer_name: bert-base-uncased
    split: train
    max_seq_length: 256
    shuffle: false
    drop_last: false
val_dataset:
  glue:
    task: mnli
    tokenizer_name: bert-base-uncased
    split: validation_matched
    max_seq_length: 256
    shuffle: false
    drop_last: false
model:
  bert_classification:
    num_labels: 3
    use_pretrained: true
    tokenizer_name: bert-base-uncased
    pretrained_model_name: bert-base-uncased
optimizer:
  decoupled_adamw:
    lr: 5.0e-5
    betas:
      - 0.9
      - 0.98
    eps: 1.0e-06
    weight_decay: 5.0e-6
schedulers:
  linear_decay_with_warmup:
    warmup_time: 0.06dur
loggers:
  tqdm: {}
max_duration: 3ep
train_batch_size: 48
eval_batch_size: 48
seed: 19
device:
  gpu: {}
dataloader:
  pin_memory: true
  persistent_workers: true
  num_workers: 8
  timeout: 0
  prefetch_factor: 2
grad_accum: 1
precision: amp
grad_clip_norm: None
validate_every_n_batches: 2300
validate_every_n_epochs: 1
save_folder: bert_checkpoints
save_interval: "100ba"
callbacks:
  run_directory_uploader:
    provider: "GOOGLE_STORAGE"
    container: "bert_checkpoints"
    key_environ: KEY
    secret_environ: SECRET
load_path: https://storage.googleapis.com/llm_checkpoints/bert_checkpoint/bert_checkpoints/ep7.pt
load_weights_only: true
load_strict_model_weights: false
load_chunk_size: 8192
