train_dataset:
  imagenet:
    resize_size: -1
    crop_size: 224
    is_train: true
    datadir: /datasets/ImageNet
    shuffle: true
    drop_last: true
val_dataset:
  imagenet:
    resize_size: 256
    crop_size: 224
    is_train: false
    datadir: /datasets/ImageNet
    shuffle: false
    drop_last: false
optimizer:
  decoupled_sgdw:
    lr: 2.048
    momentum: 0.875
    weight_decay: 5.0e-4
    dampening: 0
    nesterov: false
schedulers:
  - cosine_decay_with_warmup:
      t_warmup: "8ep"
model:
  resnet:
    model_name: resnet50
    initializers:
      - kaiming_normal
      - bn_uniform
    num_classes: 1000
<<<<<<< HEAD
max_duration: 10ep
eval_interval: 11ep
train_batch_size: 128
eval_batch_size: 64
=======
max_duration: 90ep
train_batch_size: 2048
eval_batch_size: 2048
>>>>>>> f0e2a4d7302ea8313e6a65cd2e0026c7ec0e1903
seed: 17
device:
  gpu: {}
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
grad_accum: 1
<<<<<<< HEAD
precision: fp32
=======
precision: amp
>>>>>>> f0e2a4d7302ea8313e6a65cd2e0026c7ec0e1903
