train_dataset:
  coco_mmdet:
    split: train
    shuffle: true
    drop_last: true
val_dataset:
  coco_mmdet:
    split: val
    shuffle: false
    drop_last: false
optimizers:
  decoupled_sgdw:
    lr: 0.01
    momentum: 0.9
    weight_decay: 5.0e-4
    dampening: 0
    nesterov: true
schedulers:
  - cosine_decay_with_warmup:
      t_warmup: "32ep"
model:
  yolox:
    model_name: "yolox-s"
max_duration: 300ep
train_batch_size: 16
eval_batch_size: 16
grad_accum: 1
seed: 1337
dataloader:
  pin_memory: false
  timeout: 0
  prefetch_factor: 2
  persistent_workers: false
  num_workers: 8
